### ISSUE TITLE
Adding Modules

### ISSUE THREAD

**Issue by jeswcollins** [chgeuer/HostingPerlOnAzure#1]
Is it similarly straightforward to add Perl modules?

For example, after installing Strawberry Perl according to your directions, can one install CPAN and use that to install other packages?  I.e. can one install XS CPAN  on Azure and use it to add packages?

From http://www.cpan.org/modules/INSTALL.html: "It includes a compiler and pre-installed modules that offer the ability to install XS CPAN modules directly from CPAN. cpanm can be installed by running cpan App::cpanminus. "

Actually I'm particularly interested in a few packages: BioPerl, JSON, and List. BioPerl directions include the possibility of installation from a .zip here: http://bioperl.org/DIST/. Directions here:http://www.bioperl.org/wiki/Installing_BioPerl_on_Windows#Installation_using_CPAN_or_manual_installation. So my guess this is similar to your directions?

**Comment by chgeuer** [comment]
This repo is quite old now. If I would do it again, I'd use startup tasks (https://msdn.microsoft.com/en-us/library/azure/Hh180155.aspx), instead of doing the installation of Perl in C# code in the Startup() function. 

As part of that, you can also run your CPAN module installation. In the end, it's "just" a Windows box.
